service: theme
runtime: php55
api_version: 1

handlers:

- url: /(.+\.(html|css|js|gif|png|jpg|css|ico|txt|htm|js|ttf|woff|etc|svg|ico))$
  static_files: docs/\1
  upload: .+\.(html|css|js|gif|png|jpg|css|ico|txt|htm|js|ttf|woff|etc||ico)$
  application_readable: true
  secure: optional

- url: /
  script: dispatcher.php

- url: /(.+)$
  script: dispatcher.php


skip_files:
- ^doc/.*$
- ^grunt/.*$
- ^js/.*$
- ^src/.*$
- ^buckets/.*$
- ^tests/.*$
- ^vm/.*$
- ^third-party/.*$
- ^composer\.*$
- local_config.json
- ^tmp/.*$
- ^node_modules/.*$
- ^sh_bucket_upload